services:
  - type: web
    name: flask-qr-scanner
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    dockerfilePath: ./Dockerfile
